blueprint:
  name: "Piscine - Filtration + Alertes avec notification"
  description: >
    Gère la filtration automatique de la piscine avec différents modes selon la saison (mode Été ou Hiver).

    En mode Été : filtration avec horaire de début, de fin, et pause intermédiaire possible.
    En mode Hiver : filtration simple avec heure de début et de fin.

    La pompe peut être désactivée manuellement via un interrupteur virtuel.
    En fin de cycle, un message Telegram ou mobile est envoyé avec les relevés de température, pH et redox (si capteurs renseignés).

    En cas de dépassement de seuils critiques (T°, pH, Redox), une alerte est également envoyée.
  domain: automation
  input:
    mode_saison:
      name: Mode de fonctionnement
      description: >
        Choisissez le mode selon la saison :
        - Mode "Filtration été" avec possibilité de pause
        - Mode "Filtration hiver" sans pause
      selector:
        select:
          options:
            - label: "Filtration été (avec pause possible)"
              value: ete
            - label: "Filtration hiver (continue)"
              value: hiver

    disable_switch:
      name: Arrêt manuel (facultatif)
      description: >
        Entité de type interrupteur virtuel (input_boolean) permettant de suspendre la filtration
        manuellement, même si les horaires sont atteints.
      default: null
      selector:
        entity:
          domain: input_boolean

    start_time:
      name: Heure de début de filtration
      selector:
        time:
    end_time:
      name: Heure de fin de filtration
      selector:
        time:

    pause_start:
      name: Heure de début de pause (mode été uniquement)
      description: Plage horaire pendant laquelle la filtration est temporairement coupée.
      default: ""
      selector:
        time:
    pause_end:
      name: Heure de fin de pause (mode été uniquement)
      default: ""
      selector:
        time:

    switch_pompe:
      name: Interrupteur/prise de la pompe de filtration
      selector:
        entity:
          domain: switch

    sensor_temp_eau:
      name: Capteur de température de l'eau
      selector:
        entity:
          domain: sensor
          device_class: temperature

    sensor_ph:
      name: Capteur de pH (facultatif)
      default: ""
      selector:
        entity:
          domain: sensor

    sensor_redox:
      name: Capteur de Redox (facultatif)
      default: ""
      selector:
        entity:
          domain: sensor

    sensor_temp_poolhouse:
      name: Capteur température pool house (facultatif)
      default: ""
      selector:
        entity:
          domain: sensor

    seuil_temp_eau:
      name: Température max autorisée de l'eau (en °C)
      default: 30
      selector:
        number:
          min: 0
          max: 50
          step: 0.1
    seuil_ph_min:
      name: Seuil pH minimum autorisé
      default: 7.1
      selector:
        number:
          min: 6
          max: 8
          step: 0.05
    seuil_ph_max:
      name: Seuil pH maximum autorisé
      default: 7.4
      selector:
        number:
          min: 6
          max: 8
          step: 0.05
    seuil_redox:
      name: Redox minimum autorisé (en mV)
      default: 600
      selector:
        number:
          min: 0
          max: 1000
          step: 10

    notification_target:
      name: Cible(s) de notification (Telegram, mobile, etc.)
      selector:
        target:
          entity:
            domain: notify
