blueprint:
  name: "Piscine - Filtration + Alertes avec notification"
  description: >
    Gère la filtration de piscine selon des horaires configurables.
    Envoie un message à l'arrêt avec les valeurs mesurées.
    Envoie aussi une alerte si seuils critiques dépassés (T°, pH, Redox).
    Choix entre Telegram, mobile ou les deux. Pause filtration possible.
  domain: automation
  input:
    start_time:
      name: Heure début filtration
      selector:
        time:
    end_time:
      name: Heure fin filtration
      selector:
        time:

    pause_start:
      name: Heure début de pause (optionnel)
      default: ""
      selector:
        time:
    pause_end:
      name: Heure fin de pause (optionnel)
      default: ""
      selector:
        time:

    switch_pompe:
      name: Relais pompe
      selector:
        entity:
          domain: switch

    sensor_temp_eau:
      name: Capteur température eau
      selector:
        entity:
          domain: sensor
          device_class: temperature
    sensor_ph:
      name: Capteur pH
      selector:
        entity:
          domain: sensor
    sensor_redox:
      name: Capteur Redox
      selector:
        entity:
          domain: sensor
    sensor_temp_poolhouse:
      name: Capteur température pool house
      selector:
        entity:
          domain: sensor
          device_class: temperature

    seuil_temp_eau:
      name: Seuil T° max eau
      default: 30
      selector:
        number:
          min: 0
          max: 50
          step: 0.1
    seuil_ph_min:
      name: Seuil pH min
      default: 7.1
      selector:
        number:
          min: 6
          max: 8
          step: 0.05
    seuil_ph_max:
      name: Seuil pH max
      default: 7.4
      selector:
        number:
          min: 6
          max: 8
          step: 0.05
    seuil_redox:
      name: Seuil Redox min (mV)
      default: 600
      selector:
        number:
          min: 0
          max: 1000
          step: 10

    notification_target:
      name: Cible(s) de notification
      selector:
        target:
          entity:
            domain: notify

trigger:
  - platform: time
    at: !input start_time
    id: start
  - platform: time
    at: !input end_time
    id: stop

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: start
          - condition: or
            conditions:
              - condition: template
                value_template: >
                  {{ (not pause_start or not pause_end) or (now().time() < strptime(pause_start, '%H:%M:%S').time()) or (now().time() > strptime(pause_end, '%H:%M:%S').time()) }}
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input switch_pompe

      - conditions:
          - condition: trigger
            id: stop
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input switch_pompe

          - variables:
              t: "{{ states(sensor_temp_eau) | float }}"
              ph: "{{ states(sensor_ph) | float }}"
              redox: "{{ states(sensor_redox) | float }}"
              t_pool: "{{ states(sensor_temp_poolhouse) | float }}"
              rapport: >
                🏊 Pompe de la piscine **arrêtée**.\n🔍 État relevé :\n
                - 🌡️ Eau : {{ t }} °C\n
                - 💧 pH : {{ ph }}\n
                - ⚡ Redox : {{ redox }} mV\n
                - 🏠 Pool House : {{ t_pool }} °C
              alertes: >
                {% set lignes = [] %}
                {% if t > seuil_temp_eau %}
                  {% set lignes = lignes + ["- 🌡️ Température trop élevée : " ~ t ~ " °C"] %}
                {% endif %}
                {% if ph < seuil_ph_min or ph > seuil_ph_max %}
                  {% set lignes = lignes + ["- 💧 pH hors plage : " ~ ph ~ " (attendu entre " ~ seuil_ph_min ~ " et " ~ seuil_ph_max ~ ")"] %}
                {% endif %}
                {% if redox < seuil_redox %}
                  {% set lignes = lignes + ["- ⚡ Redox trop faible : " ~ redox ~ " mV (attendu ≥ " ~ seuil_redox ~ ")"] %}
                {% endif %}
                {{ lignes | join('\n') }}

          - service: notify.send_message
            data:
              target: !input notification_target
              message: "{{ rapport }}"

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ alertes | length > 0 }}"
                sequence:
                  - service: notify.send_message
                    data:
                      target: !input notification_target
                      message: >
                        ⚠️ **Alerte Piscine - Valeurs critiques détectées**\n{{ alertes }}\n
                        ➤ Merci de vérifier la qualité de l’eau.
mode: single